server:
  port: 8990
spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/RefuelingWuhan?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    #username: root
    #password: 123456
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.211.55.10:1521:orcl
    username: haiyangep
    password: lnsoft
